version: '3.8'
services:
  mongodb:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./config/development.env
  frontend:
    image: 'notes-frontend-dev'
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
  backend:
    image: 'notes-backend-dev'
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    env_file:
      - ./config/development.env
volumes:
  mongo-data:
    driver: local
